import mongoose from "mongoose";

const messageSchema = new mongoose.Schema(
  {
    conversationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Conversation",
      required: true,
    },
    sender: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    /**
     * `system` messages are generated by the platform (e.g. "Listing marked
     * sold") and render as a centred chip rather than a bubble.
     */
    kind: {
      type: String,
      enum: ["text", "image", "system"],
      default: "text",
    },
    text: {
      type: String,
      trim: true,
      maxlength: 2000,
      default: "",
    },
    imageUrl: { type: String, trim: true, default: "" },
    readAt: { type: Date, default: null },
  },
  { timestamps: true }
);

messageSchema.index({ conversationId: 1, createdAt: 1 });
messageSchema.index({ conversationId: 1, sender: 1, readAt: 1 });

messageSchema.pre("validate", function requireContent(next) {
  if (this.kind === "image" ? !this.imageUrl : !this.text) {
    next(new Error("A message must contain text or an image."));
    return;
  }
  next();
});

const Message = mongoose.model("Message", messageSchema);

export default Message;
